sonar.projectKey=taha2samy_bigfeat
sonar.organization=taha2samy
sonar.sources=bigfeat
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml