name: SonarCloud Quality Review

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Code Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

    
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
        with:
          args: >
            -Dsonar.projectKey=taha2samy_bigfeat
            -Dsonar.organization=taha2samy
            -Dsonar.sources=bigfeat
            -Dsonar.python.version=3.10
            -Dsonar.exclusions=benchmarking/**,tests/**,docs/**,metafeatures_training/**